### ISSUE TITLE
Error using gtburst

### ISSUE THREAD

**Issue by Jisans** [fermi-lat/Fermitools-conda#135]
Hello everyone, when I use the gtburst to download Fermi LAT data, I get an error.The specific gtburst.log file is as follows
```
Analysis started at 2022-10-13 16:23:38 by user jian

--------------------------------------------------
Welcome to the Fermi Burst Analysis GUI v. 03-00-00p5!
Credits: G.Vianello (giacomov@slac.stanford.edu), N.Omodei (nicola.omodei@gmail.com)
This software embeds:
 -gtapps_mp by J. Perkins (http://fermi.gsfc.nasa.gov/ssc/data/analysis/user/)
 -APlpy                   (http://aplpy.github.io/)
These packages are property of the respective authors.
-------------------------------------------------
Use the -fast flag when running gtburst to speed up the code
 (the coinsole will not be captured in the GUI) 
-------------------------------------------------
Query parameters:
                    coordfield = 204.9,-8.4
                   coordsystem = J2000
                    shapefield = 60.0
                     timefield = 256534404.558,256549404.558
                      timetype = MET
                   energyfield = 30,1000000
        photonOrExtendedOrNone = Extended
                   destination = query
                    spacecraft = checked
url query: https://fermi.gsfc.nasa.gov/cgi-bin/ssc/LAT/LATDataQuery.cgi?coordfield=204.9%2C-8.4&coordsystem=J2000&shapefield=60.0&timefield=256534404.558%2C256549404.558&timetype=MET&energyfield=30%2C1000000&photonOrExtendedOrNone=Extended&destination=query&spacecraft=checked

Answer from the LAT data server:





Estimated Time For The Query....: 77.0
done
Local data repository (destination): /home/jian/FermiData/bn090217206 (already existent)
Retrieving L22101304284572741BED98_EV00.fits ...  done
Retrieving L22101304284572741BED98_SC00.fits ...  done

Download files done!
Writing /home/jian/FermiData/bn090217206/gll_cspec_tr_bn090217206_v00.rsp...
time -p gtselect infile=/home/jian/FermiData/bn090217206/gll_ft1_tr_bn090217206_v00.fit outfile=__temp_ft1.fits ra=204.9 dec=-8.4 rad=15.0 tmin=256538403.558 tmax=256540405.558 emin=10.0 emax=300000.0 zmin=0.0 zmax=110.0 evclass="INDEF" evtype="INDEF" convtype=-1 phasemin=0.0 phasemax=1.0 evtable="EVENTS" chatter=2 clobber=yes debug=no gui=no mode="ql"
/bin/sh: 1: time: not found
Writing /home/jian/FermiData/bn090217206/gll_cspec_tr_bn090217206_v00.pha...
 *  Get energy binning from the response matrix...
-------------- EXCEPTION ---------------------------

Snap! An unhandled exception has occurred at line 147 of file gtburst.py.

The program will try to continue running. If you think this is a bug, send a message to fermihelp@milkyway.gsfc.nasa.gov attaching your gtburst.log file.

The full traceback has been saved to the log and printed in the console.

Traceback (most recent call last):
  File "/home/jian/miniconda3/envs/fermi3ML/lib/python3.9/site-packages/fermitools/gtburst.py", line 137, in handle_exception
    return method(*args, **kwargs)
  File "/home/jian/miniconda3/envs/fermi3ML/lib/python3.9/site-packages/fermitools/gtburst.py", line 1588, in downloadDataSetFromFTP
    downloader.getFTP()
  File "/home/jian/miniconda3/envs/fermi3ML/lib/python3.9/site-packages/fermitools/GtBurst/downloadTransientData.py", line 342, in getFTP
    dataHandling._makeDatasetsOutOfLATdata(newFilenames['ft1'],newFilenames['ft2'],
  File "/home/jian/miniconda3/envs/fermi3ML/lib/python3.9/site-packages/fermitools/GtBurst/dataHandling.py", line 652, in _makeDatasetsOutOfLATdata
    gtllebin(**parameters)
  File "/home/jian/miniconda3/envs/fermi3ML/lib/python3.9/site-packages/fermitools/GtBurst/commands/gtllebin.py", line 56, in gtllebin
    run(**kwargs)
  File "/home/jian/miniconda3/envs/fermi3ML/lib/python3.9/site-packages/fermitools/GtBurst/commands/gtllebin.py", line 95, in run
    lleData                     = dataHandling.LLEData(eventfile,rspfile,ft2file)
  File "/home/jian/miniconda3/envs/fermi3ML/lib/python3.9/site-packages/fermitools/GtBurst/dataHandling.py", line 781, in __init__
    raise IOError("File %s does not exist!" % (eventFile))
OSError: File __temp_ft1.fits does not exist!

-------------- EXCEPTION ---------------------------
-------------- EXCEPTION ---------------------------

Snap! An unhandled exception has occurred at line 147 of file gtburst.py.

The program will try to continue running. If you think this is a bug, send a message to fermihelp@milkyway.gsfc.nasa.gov attaching your gtburst.log file.

The full traceback has been saved to the log and printed in the console.

Traceback (most recent call last):
  File "/home/jian/miniconda3/envs/fermi3ML/lib/python3.9/site-packages/fermitools/gtburst.py", line 137, in handle_exception
    return method(*args, **kwargs)
  File "/home/jian/miniconda3/envs/fermi3ML/lib/python3.9/site-packages/fermitools/gtburst.py", line 1105, in run
    self.root.mainloop()
  File "/home/jian/miniconda3/envs/fermi3ML/lib/python3.9/tkinter/__init__.py", line 1429, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt

-------------- EXCEPTION ---------------------------

```

**Note:**
OS: Linux DESKTOP-10UCA6U 5.15.68.1-microsoft-standard-WSL2 #1 SMP Mon Sep 19 19:14:52 UTC 2022 x86_64 GNU/Linux
Python V 3.9.13
pip V 22.2.2
Fermitools V 2.2.0    
fermitools-data V 0.18

**Comment by omodei** [comment]
From your error log"/bin/sh: 1: time: not found"
It looks like you don't have the "time" shell command installed, which is very strange as I think it comes with every unix/linux distribution. time program can be installed as: 
apt-get install time
All that said, are you sure your system's sh is pointing to bash?

**Comment by Jisans** [comment]
Problem solved, thanks to all developers!
