### ISSUE TITLE
I got the issue of IndexError: list index out of range when using gtlike for analysis, and reinstalling fermipy didn't get it fixed either 

### ISSUE THREAD

**Issue by dahe12345** [fermi-lat/Fermitools-conda#161]
fermipy version 1.2.2
ScienceTools version 2.2.0
2024-03-11 01:58:46 INFO GTAnalysis.setup(): Running setup.
2024-03-11 01:58:46 INFO GTBinnedAnalysis.setup(): Running setup for component 00
2024-03-11 01:58:46 INFO GTBinnedAnalysis.run_gtapp(): Running gtselect.
2024-03-11 01:58:46 INFO GTBinnedAnalysis.run_gtapp(): time -p gtselect infile=/home//Desktop/hwtpractice/fermi_data_sed/Results/3119_4FGL_J1422_3_3223_py3712_OQ334_SED_663552002.0_663638402.0/evfile_00.txt outfile=/home//Desktop/hwtpractice/fermi_data_sed/Results/3119_4FGL_J1422_3_3223_py3712_OQ334_SED_663552002.0_663638402.0/ft1_00.fits ra=215.5771942138672 dec=32.3911018371582 rad=11.106601717798213 tmin=663552002.0 tmax=663638402.0 emin=100.0 emax=300000.0 zmin=0.0 zmax=90.0 evclass=128 evtype=3 convtype=-1 phasemin=0.0 phasemax=1.0 evtable="EVENTS" chatter=3 clobber=yes debug=no gui=no mode="ql"
2024-03-11 01:58:46 INFO GTBinnedAnalysis.run_gtapp(): This is gtselect version HEAD
2024-03-11 01:58:46 INFO GTBinnedAnalysis.run_gtapp(): Caught N3tip12TipExceptionE at the top level: File not in FITS format: /home//Desktop/hwtpractice/fermi_data_sed/Results/3119_4FGL_J1422_3_3223_py3712_OQ334_SED_663552002.0_663638402.0/
2024-03-11 01:58:46 INFO GTBinnedAnalysis.run_gtapp(): Finished gtselect. Execution time: 0.11 s
2024-03-11 01:58:46 INFO GTBinnedAnalysis.run_gtapp(): Running gtltcube.
2024-03-11 01:58:46 INFO GTBinnedAnalysis.run_gtapp(): time -p gtltcube evfile="/home//Desktop/hwtpractice/fermi_data_sed/Results/3119_4FGL_J1422_3_3223_py3712_OQ334_SED_663552002.0_663638402.0/ft1_00.fits" evtable="EVENTS" scfile=/home//Desktop/hwtpractice/fermi_data_sed/data/L240301092222BC1FB74802_SC00.fits sctable="SC_DATA" outfile=/home//Desktop/hwtpractice/fermi_data_sed/Results/3119_4FGL_J1422_3_3223_py3712_OQ334_SED_663552002.0_663638402.0/ltcube_00.fits dcostheta=0.025 binsz=1.0 phibins=0 tmin=0.0 tmax=0.0 file_version="1" zmin=0.0 zmax=90.0 chatter=2 clobber=yes debug=no gui=no mode="ql"
2024-03-11 01:58:46 INFO GTBinnedAnalysis.run_gtapp(): Caught St13runtime_error at the top level: File not found: /home//Desktop/hwtpractice/fermi_data_sed/Results/3119_4FGL_J1422_3_3223_py3712_OQ334_SED_663552002.0_663638402.0/ft1_00.fits
2024-03-11 01:58:46 INFO GTBinnedAnalysis.run_gtapp(): Finished gtltcube. Execution time: 0.05 s
Traceback (most recent call last):
File "/home//Desktop/hwtpractice/fermi_data_sed/sed/000_fermipy_sed_data/Fermipy_SED_1-300GeV.py", line 227, in
gta.setup(overwrite=True)
File "/home//mambaforge/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 1087, in setup
c.setup(overwrite=overwrite)
File "/home//mambaforge/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 5176, in setup
self._ltc = LTCube.create(self.files['ltcube'])
File "/home//mambaforge/envs/fermipy/lib/python3.9/site-packages/fermipy/ltcube.py", line 192, in create
ltc = cls.create_from_fits(files[0])
IndexError: list index out of range

**Comment by nmirabal** [comment]
This is a fermipy issue. Please post it at the following link
https://github.com/fermiPy/fermipy/issues
