### ISSUE TITLE
GtBurst not responding.

### ISSUE THREAD

**Issue by nyctophile-aayu** [fermi-lat/Fermitools-conda#168]
GtBurst is not opening with fermi environment, generating error:
(fermi) lonewolf@lonewolf-HP-Z2-Tower-G9-Workstation-Desktop-PC:~/Ayush$ gtburst

Loading pyBurstAnalysisGUI v. 03-00-00p5 Traceback (most recent call last):
  File "/home/lonewolf/miniforge3/envs/fermi/bin/gtburst", line 7, in <module>
    from fermitools.gtburst import main
  File "/home/lonewolf/miniforge3/envs/fermi/lib/python3.9/site-packages/fermitools/gtburst.py", line 20, in <module>
    import matplotlib
  File "/home/lonewolf/miniforge3/envs/fermi/lib/python3.9/site-packages/matplotlib/__init__.py", line 131, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/home/lonewolf/miniforge3/envs/fermi/lib/python3.9/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/home/lonewolf/miniforge3/envs/fermi/lib/python3.9/site-packages/matplotlib/colors.py", line 51, in <module>
    from PIL import Image
  File "/home/lonewolf/miniforge3/envs/fermi/lib/python3.9/site-packages/PIL/Image.py", line 68, in <module>
    from ._typing import StrOrBytesPath, TypeGuard
  File "/home/lonewolf/miniforge3/envs/fermi/lib/python3.9/site-packages/PIL/_typing.py", line 10, in <module>
    NumpyArray = npt.NDArray[Any]
AttributeError: module 'numpy.typing' has no attribute 'NDArray'

When I am using fermipy then it is opening the GtBurst interface but after selecting the GRB source, it hung and do not process any further. I have attached the log file and screenshot of GtBurst. I am using python 3.9.* for Linux 22.0.
[gtburst.log](https://github.com/user-attachments/files/17187148/gtburst.log)
![Screenshot from 2024-09-30 14-34-54](https://github.com/user-attachments/assets/1091edc5-5f65-4afd-91f2-36d62fbd5e8a)

**Comment by nmirabal** [comment]
Are you launching within python?. Gtburst is a GUI and should be launched from a terminal after activating the Fermitools

**Comment by jasercion** [comment]
@nyctophile-aayu Can you please try this again with the latest version of the Fermitools?  Hopefully the updates we've made should take care of this issue.

**Comment by jasercion** [comment]
Assumed fixed/superceded.  Reopen and tag me if issue unresolved.
