### ISSUE TITLE
gtltcube execution failed during light curve generation

### ISSUE THREAD

**Issue by Sanjuphysics12** [fermi-lat/Fermitools-conda#39]
I was trying to generate the light curve, after generation of few bins (fits file)  I got the following error:

Caught St13runtime_error at the top level: No GTIs found in input event file(s).
Traceback (most recent call last):
  File "lightflux.py", line 9, in <module>
    lc.generate_files()
  File "/path/LightCurve.py", line 91, in generate_files
    expCube.run()
  File "/pathl/anaconda2/envs/fermi/lib/python2.7/site-packages/fermitools/GtApp.py", line 76, in run
    raise RuntimeError, self.appName + " execution failed"
RuntimeError: gtltcube execution failed

Kindly tell me how to resolve this issue.

**Comment by Sanjuphysics12** [comment]
@nmirabal  I checked for larger time interval even I did the following.
     Suppose start_time: A, stop_time: K and interval is consecutive alphabets, e.g. A to B, B to C, C to D ......J to K. Let us consider there is no valid data within I to J, so I would get the above error during the running of gtltcube command for the interval I to J.  Now, I set stop_time: I instead of K, then I am getting the following error:


Attempt to set the value outside of existing bounds.
Value -nan is not between 0.001 and 1000
Traceback (most recent call last):
  File "lightflux.py", line 11, in <module>
    lc.runLikelihood()
  File "/(path)/Light Curve/LightCurve.py", line 140, in runLikelihood
    like.fit(verbosity=0,covar=True,optObject=likeObj)
  File "/(path)/anaconda2/envs/fermi/lib/python2.7/site-packages/fermitools/AnalysisBase.py", line 77, in fit
    optObject=optObject, numericDerivs=numericDerivs)
  File "/(path)/anaconda2/envs/fermi/lib/python2.7/site-packages/fermitools/AnalysisBase.py", line 122, in _errors
    myOpt.find_min(verbosity, tol, self.tolType)
  File "/(path)/anaconda2/envs/fermi/lib/python2.7/site-packages/fermitools/pyLikelihood.py", line 4289, in find_min
    return _pyLikelihood.NewMinuit_find_min(self, *args)
RuntimeError: Attempt to set the value outside of existing bounds.

  In both cases, I got the above error.

**Comment by nmirabal** [comment]
Can you download two weeks of data for your source and run the following analysis thread?
https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/python_tutorial.html
Please let me know if that works.
