### ISSUE TITLE
pointlike problem astro::SkyDir

### ISSUE THREAD

**Issue by imereu** [fermi-lat/Fermitools-conda#55]
Hi,
I have tried to do a likelihood exercise following the tutorial 
[http://polywww.in2p3.fr/activites/physique/glast/workbook/pages/sciTools_pointlike_tutorial/3_pointlike_tutorial_part02.html#performSpectralAnalysis ](url)

I find this error:

`Using gti from expCube.fits
loaded LivetimeCube expCube.fits 
.....loading binfile binned_4bpd.fits ...Creating Bands, pixels from file binned_4bpd.fits, tables BANDS, PIXELS
  GTI interval: 243756000-259308000, on time: 1.26539e+07 s
 found 26 bands, energies 100-1000000 MeV
.....setting up point sources (12 in ROI)... done!
.....setting up diffuse/extended backgrounds for 24 bands...
.......... EG_v02 ...convolving band  1/24
Traceback (most recent call last):
  File "pointlike_test.py", line 31, in <module>
    xmlfile = "example_3C454-srcModel.xml")
  File "/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermitools/uw/like/pointspec.py", line 286, in roi
    return ROIAnalysis(roi_dir,psm,dsm,self,**kwargs)
  File "/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermitools/uw/like/roi_analysis.py", line 82, in __init__
    self.__setup_bands__()
  File "/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermitools/uw/like/roi_analysis.py", line 127, in __setup_bands__
    if not self.skip_setup: self.__setup_counts__()
  File "/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermitools/uw/like/roi_analysis.py", line 131, in __setup_counts__
    self.dsm.setup_initial_counts(self.bands)
  File "/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermitools/uw/like/roi_managers.py", line 286, in setup_initial_counts
    bg.initialize_counts(bands)
  File "/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermitools/uw/like/roi_diffuse.py", line 270, in initialize_counts
    myband.pi_evals[:,ne] = self._pix_value(band.wsdl)
  File "/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermitools/uw/like/roi_diffuse.py", line 328, in _pix_value
    return self.active_bgc(pixlist,self.active_bgc.cvals)
  File "/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermitools/uw/utilities/convolution.py", line 122, in __call__
    PythonUtilities.rot_grid(rvals,skydir,self.center)
TypeError: in method 'PythonUtilities_rot_grid', argument 3 of type 'std::vector< astro::SkyDir,std::allocator< astro::SkyDir > > const'`

**Comment by imereu** [comment]
Is there still no solution to this problem or has it been solved?

**Comment by donhorner** [comment]
Sorry. I saw that Toby seemed to be trying to help you on Slack so never followed up here. 

The problem is no one in FSSC knows anything about pointlike.  It's entirely Toby's tool.  We've never really officially supported it.  It wasn't even included the Science Tools (except for one release).  It looks like Toby was stuck trying to get the Fermitools installed as he wanted.  I can prod them to see if there's any progress.
